#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then xmodmap "$usermodmap"
fi 

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset 
fi

#### SYSTEM REQUIREMENTS CONFIGS ###
# Setting resolutions
xrandr --auto

# Compositor
picom &
### END ###

### Customizations for DWM ###
# For dwm info bar
#dwm_bar.sh &
slstatus &

# Background random slideshow for User michaelkik
oxygen --imagesrc=/Pictures --timeout=300 --monitors=1 & 
nitrogen --restore

# FCITX
#fcitx5 &

# Drive speed for CD Drive
eject -x 12 /dev/sr0

### END ###

# Execute DWM
exec dwm 
