import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM= "xterm-256color"

# Old color scheme
#[colors.bright]
#black = "#686868"
#blue = "#59C2FF"
#cyan = "#95E6CB"
#green = "#C2D94C"
#magenta = "#FFEE99"
#red = "#F07178"
#white = "#FFFFFF"
#yellow = "#FFB454"
#
#[colors.normal]
#black = "#01060E"
#blue = "#53BDFA"
#cyan = "#90E1C6"
#green = "#91B362"
#magenta = "#FAE994"
#red = "#EA6C73"
#white = "#C7C7C7"
#yellow = "#F9AF4F"
#
#[colors.primary]
#background = "#0A0E14"
#foreground = "#B3B1AD"
#

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 12

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[selection]
save_to_clipboard = false

[window]
opacity = 0.5

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2
